[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.50"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo -DF"

[context.deploy-preview.environment]
HUGO_VERSION = "0.50"

[context.branch-deploy]
command = "hugo -DF"

[context.branch-deploy.environment]
HUGO_VERSION = "0.50"